# Generated by Django 5.0 on 2024-05-14 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('next_fetch_at', models.DateTimeField(null=True)),
                ('last_fetch_at', models.DateTimeField(null=True)),
                ('last_post_date', models.CharField(max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['next_fetch_at'], name='news_resour_next_fe_8c81ef_idx'), models.Index(fields=['last_fetch_at'], name='news_resour_last_fe_2a8603_idx'), models.Index(fields=['last_post_date'], name='news_resour_last_po_555f57_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.resource')),
            ],
        ),
    ]
