# Generated by Django 5.0 on 2024-05-14 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['abbreviation'], name='currency_cu_abbrevi_a23adc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_symbol', models.CharField(max_length=30)),
                ('second_symbol', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['first_symbol'], name='currency_pr_first_s_5fe7b7_idx'), models.Index(fields=['second_symbol'], name='currency_pr_second__131c43_idx'), models.Index(fields=['amount'], name='currency_pr_amount_603055_idx'), models.Index(fields=['first_symbol', 'second_symbol'], name='currency_pr_first_s_a724cb_idx')],
            },
        ),
    ]
