# Generated by Django 5.0 on 2024-05-14 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_personal', models.BooleanField(default=True)),
                ('info', models.JSONField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 3, 18, 106500))),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.channel')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.message')),
            ],
        ),
    ]
